Added support for wire transfers
bigdawgbank/ie-bank pull request #21
Opened 2024-11-27 22:00 UTC by ADRIANDLT

Added support to be able to transfer money from one user account to another account from a different user (Wire Transfers)

2024-11-27 22:06 UTC, RestartDK commented
Please resolve conflicts before merge @ADRIANDLT

2024-11-28 13:42 UTC, RestartDK requested changes
Ok so I put down what you have to change in the code. But some other stuff

Can you instead of manually entering the account code show all the possible accounts you could send it to and who owns it? Because right now you have the `/accounts/all` route that is redundant in your backend.

lmk @ADRIANDLT

2024-11-28 13:42 UTC, RestartDK commented on backend/iebank_api/routes.py
> +            # then we will need to create a new class named BankWireTransfer
Please remove this comment

2024-11-28 13:42 UTC, RestartDK commented on frontend/src/api.js
> +  async getUserAccounts() {
rename this back to `getAccounts()`

2024-11-28 13:42 UTC, RestartDK commented on frontend/src/components/AppAccounts.vue
> +        const response = await accountService.getUserAccounts();
Rename to `getAccounts()`

2024-11-28 13:42 UTC, RestartDK commented on frontend/src/components/Transfer.vue
> +        const response = await accountService.getUserAccounts();
Rename this to `getAccounts`

2024-11-28 13:42 UTC, RestartDK commented on frontend/src/components/WireTransfer.vue
> +          //alert(this.accounts[0].account_number);
Remove the comments

```suggestion
          const response = await accountService.getUserAccounts();
          console.log(response);
          this.accounts = response.accounts;
```

2024-11-28 14:13 UTC, ADRIANDLT commented
> Ok so I put down what you have to change in the code. But some other stuff
> 
> Can you instead of manually entering the account code show all the possible accounts you could send it to and who owns it? Because right now you have the `/accounts/all` route that is redundant in your backend.
> 
> lmk @ADRIANDLT

Usually in a real bank app/website when you are doing bank wire-transfers you manually type the account number/IBAN so you have the user who is receiving their money give their account number to the sender. The only case where you have a dropdown menu with all the accounts that you can send money to, is when you are transferring money between user account´s/your own accounts.

2024-11-28 14:56 UTC, RestartDK approved these changes
Looks good now

2024-11-28 16:01 UTC, merged